# Generated by Django 6.0.5 on 2026-06-22 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskman', '0005_alter_task_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
